language: php
 
- php: 7.1
  env: REPORT_TESTS_COVERAGE=1

before_script:
  - composer self-update
  - composer install --no-interaction
script:
  - vendor/bin/phpunit
after_success:
  #- if [ $REPORT_TESTS_COVERAGE == 1 ]; then php vendor/bin/test-reporter --coverage-report=./tests/storage/logs/test-reports/clover.xml; fi
  - if [ $REPORT_TESTS_COVERAGE == 1 ]; then php vendor/bin/coveralls -v; fi
#addons:
#  code_climate:
#    repo_token: CODECLIMATE_REPO_TOKEN
notifications:
  email: true